package com.mycaruae.app.feature.reminders

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.mycaruae.app.data.database.entity.ReminderEntity
import com.mycaruae.app.data.datastore.UserPreferences
import com.mycaruae.app.data.repository.BrandRepository
import com.mycaruae.app.data.repository.ReminderRepository
import com.mycaruae.app.data.repository.VehicleRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.concurrent.TimeUnit
import javax.inject.Inject

data class ExpiryInfo(
    val type: String,
    val title: String,
    val vehicleLabel: String,
    val expiryDate: Long,
    val daysRemaining: Long,
)

data class RemindersUiState(
    val expiries: List<ExpiryInfo> = emptyList(),
    val manualReminders: List<ReminderEntity> = emptyList(),
    val completedReminders: List<ReminderEntity> = emptyList(),
    val isLoading: Boolean = true,
    val hasVehicle: Boolean = false,
)

@HiltViewModel
class RemindersViewModel @Inject constructor(
    private val reminderRepository: ReminderRepository,
    private val vehicleRepository: VehicleRepository,
    private val brandRepository: BrandRepository,
    private val userPreferences: UserPreferences,
) : ViewModel() {

    private val _uiState = MutableStateFlow(RemindersUiState())
    val uiState: StateFlow<RemindersUiState> = _uiState.asStateFlow()

    init {
        loadReminders()
    }

    private fun loadReminders() {
        viewModelScope.launch {
            val userData = userPreferences.userData.first()
            val vehicles = vehicleRepository.getAllVehicles(userData.userId).first()

            if (vehicles.isEmpty()) {
                _uiState.update { it.copy(isLoading = false, hasVehicle = false) }
                return@launch
            }

            val brands = brandRepository.getAllBrands().first()
            val now = System.currentTimeMillis()

            val allExpiries = mutableListOf<ExpiryInfo>()
            val allManual = mutableListOf<ReminderEntity>()
            val allCompleted = mutableListOf<ReminderEntity>()

            vehicles.forEach { vehicle ->
                val brandName = brands.find { it.id == vehicle.brandId }?.name ?: vehicle.brandId
                val plate = vehicle.plateNumber ?: ""
                val label = "$brandName ${vehicle.modelId} ${vehicle.year}" +
                        if (plate.isNotBlank()) " • $plate" else ""

                allExpiries.add(
                    ExpiryInfo(
                        type = "REGISTRATION",
                        title = "Registration",
                        vehicleLabel = label,
                        expiryDate = vehicle.registrationExpiry,
                        daysRemaining = TimeUnit.MILLISECONDS.toDays(vehicle.registrationExpiry - now),
                    )
                )
                allExpiries.add(
                    ExpiryInfo(
                        type = "INSPECTION",
                        title = "Inspection",
                        vehicleLabel = label,
                        expiryDate = vehicle.inspectionExpiry,
                        daysRemaining = TimeUnit.MILLISECONDS.toDays(vehicle.inspectionExpiry - now),
                    )
                )

                val reminders = reminderRepository.getAll(vehicle.id).first()
                allManual.addAll(reminders.filter { !it.isAutoGenerated && it.status == "PENDING" })
                allCompleted.addAll(reminders.filter { it.status != "PENDING" && !it.isAutoGenerated })
            }

            // Sort: most urgent first
            allExpiries.sortBy { it.daysRemaining }

            _uiState.update {
                it.copy(
                    expiries = allExpiries,
                    manualReminders = allManual,
                    completedReminders = allCompleted,
                    isLoading = false,
                    hasVehicle = true,
                )
            }
        }
    }

    fun completeReminder(reminder: ReminderEntity) {
        viewModelScope.launch {
            reminderRepository.completeReminder(reminder)
        }
    }

    fun dismissReminder(reminder: ReminderEntity) {
        viewModelScope.launch {
            reminderRepository.dismissReminder(reminder)
        }
    }
}