package com.mycaruae.app.feature.reminders

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.mycaruae.app.data.database.entity.ReminderEntity
import com.mycaruae.app.data.datastore.UserPreferences
import com.mycaruae.app.data.repository.ReminderRepository
import com.mycaruae.app.data.repository.VehicleRepository
import dagger.hilt.android.lifecycle.HiltViewModel
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.flow.update
import kotlinx.coroutines.launch
import java.util.concurrent.TimeUnit
import javax.inject.Inject

data class ExpiryInfo(
    val type: String,
    val title: String,
    val expiryDate: Long,
    val daysRemaining: Long,
)

data class RemindersUiState(
    val expiries: List<ExpiryInfo> = emptyList(),
    val manualReminders: List<ReminderEntity> = emptyList(),
    val completedReminders: List<ReminderEntity> = emptyList(),
    val isLoading: Boolean = true,
    val hasVehicle: Boolean = false,
)

@HiltViewModel
class RemindersViewModel @Inject constructor(
    private val reminderRepository: ReminderRepository,
    private val vehicleRepository: VehicleRepository,
    private val userPreferences: UserPreferences,
) : ViewModel() {

    private val _uiState = MutableStateFlow(RemindersUiState())
    val uiState: StateFlow<RemindersUiState> = _uiState.asStateFlow()

    init {
        loadReminders()
    }

    private fun loadReminders() {
        viewModelScope.launch {
            val userData = userPreferences.userData.first()
            val vehicleId = userData.activeVehicleId

            if (vehicleId.isBlank()) {
                val vehicle = vehicleRepository.getVehicle(userData.userId).first()
                if (vehicle != null) {
                    loadForVehicle(vehicle.id, vehicle.registrationExpiry, vehicle.inspectionExpiry)
                } else {
                    _uiState.update { it.copy(isLoading = false, hasVehicle = false) }
                }
            } else {
                val vehicle = vehicleRepository.getVehicleByIdOnce(vehicleId)
                if (vehicle != null) {
                    loadForVehicle(vehicle.id, vehicle.registrationExpiry, vehicle.inspectionExpiry)
                } else {
                    _uiState.update { it.copy(isLoading = false, hasVehicle = false) }
                }
            }
        }
    }

    private suspend fun loadForVehicle(vehicleId: String, regExpiry: Long, inspExpiry: Long) {
        val now = System.currentTimeMillis()

        val expiries = listOf(
            ExpiryInfo(
                type = "REGISTRATION",
                title = "Registration",
                expiryDate = regExpiry,
                daysRemaining = TimeUnit.MILLISECONDS.toDays(regExpiry - now),
            ),
            ExpiryInfo(
                type = "INSPECTION",
                title = "Inspection",
                expiryDate = inspExpiry,
                daysRemaining = TimeUnit.MILLISECONDS.toDays(inspExpiry - now),
            ),
        )

        reminderRepository.getAll(vehicleId).collect { reminders ->
            val manual = reminders.filter { !it.isAutoGenerated && it.status == "PENDING" }
            val completed = reminders.filter { it.status != "PENDING" && !it.isAutoGenerated }

            _uiState.update {
                it.copy(
                    expiries = expiries,
                    manualReminders = manual,
                    completedReminders = completed,
                    isLoading = false,
                    hasVehicle = true,
                )
            }
        }
    }

    fun completeReminder(reminder: ReminderEntity) {
        viewModelScope.launch {
            reminderRepository.completeReminder(reminder)
        }
    }

    fun dismissReminder(reminder: ReminderEntity) {
        viewModelScope.launch {
            reminderRepository.dismissReminder(reminder)
        }
    }
}