package com.mycaruae.app.data.database.entity

import androidx.room.Entity
import androidx.room.ForeignKey
import androidx.room.Index
import androidx.room.PrimaryKey

@Entity(
    tableName = "reminders",
    foreignKeys = [
        ForeignKey(
            entity = VehicleEntity::class,
            parentColumns = ["id"],
            childColumns = ["vehicleId"],
            onDelete = ForeignKey.CASCADE,
        ),
    ],
    indices = [Index("vehicleId")],
)
data class ReminderEntity(
    @PrimaryKey val id: String,
    val vehicleId: String,
    val type: String,
    val title: String,
    val dueDate: Long?,
    val dueMileage: Int?,
    val recurrence: String?,
    val status: String,
    val severity: String,
    val snoozedUntil: Long?,
    val isAutoGenerated: Boolean,
    val notificationDaysBefore: Int?,
    val note: String?,
    val completedAt: Long?,
    val pendingSync: Boolean = false,
    val createdAt: Long,
    val updatedAt: Long,
)
