package com.mycaruae.app.data.repository

import com.mycaruae.app.data.database.dao.ReminderDao
import com.mycaruae.app.data.database.entity.ReminderEntity
import kotlinx.coroutines.flow.Flow
import java.util.UUID
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class ReminderRepository @Inject constructor(
    private val reminderDao: ReminderDao,
) {
    fun getAll(vehicleId: String): Flow<List<ReminderEntity>> {
        return reminderDao.getByVehicle(vehicleId)
    }

    fun getUpcoming(vehicleId: String, limit: Int = 5): Flow<List<ReminderEntity>> {
        return reminderDao.getUpcoming(vehicleId, limit)
    }

    suspend fun addReminder(
        vehicleId: String,
        type: String,
        title: String,
        dueDate: Long?,
        dueMileage: Int?,
        note: String?,
        notificationDaysBefore: Int?,
        isAutoGenerated: Boolean = false,
    ): ReminderEntity {
        val now = System.currentTimeMillis()
        val reminder = ReminderEntity(
            id = UUID.randomUUID().toString(),
            vehicleId = vehicleId,
            type = type,
            title = title,
            dueDate = dueDate,
            dueMileage = dueMileage,
            recurrence = null,
            status = "PENDING",
            severity = "NORMAL",
            snoozedUntil = null,
            isAutoGenerated = isAutoGenerated,
            notificationDaysBefore = notificationDaysBefore,
            note = note,
            completedAt = null,
            pendingSync = true,
            createdAt = now,
            updatedAt = now,
        )
        reminderDao.insert(reminder)
        return reminder
    }

    suspend fun completeReminder(reminder: ReminderEntity) {
        val now = System.currentTimeMillis()
        reminderDao.update(
            reminder.copy(
                status = "COMPLETED",
                completedAt = now,
                updatedAt = now,
            )
        )
    }

    suspend fun dismissReminder(reminder: ReminderEntity) {
        val now = System.currentTimeMillis()
        reminderDao.update(
            reminder.copy(
                status = "DISMISSED",
                updatedAt = now,
            )
        )
    }

    suspend fun clearAutoReminders(vehicleId: String, type: String) {
        reminderDao.deleteAutoByType(vehicleId, type)
    }

    suspend fun generateExpiryReminders(
        vehicleId: String,
        expiryDate: Long,
        type: String,
        title: String,
        notificationDays: Set<Int>,
    ) {
        // Clear existing auto-reminders for this type first
        clearAutoReminders(vehicleId, type)

        val now = System.currentTimeMillis()
        val dayMillis = 86_400_000L

        val reminders = notificationDays.map { days ->
            val dueDate = expiryDate - (days * dayMillis)
            val reminderTitle = if (days == 0) "$title expires today!" else "$title expires in $days days"
            ReminderEntity(
                id = UUID.randomUUID().toString(),
                vehicleId = vehicleId,
                type = type,
                title = reminderTitle,
                dueDate = dueDate,
                dueMileage = null,
                recurrence = null,
                status = if (dueDate < now) "COMPLETED" else "PENDING",
                severity = when {
                    days <= 1 -> "CRITICAL"
                    days <= 7 -> "HIGH"
                    days <= 30 -> "MEDIUM"
                    else -> "LOW"
                },
                snoozedUntil = null,
                isAutoGenerated = true,
                notificationDaysBefore = days,
                note = null,
                completedAt = if (dueDate < now) now else null,
                pendingSync = true,
                createdAt = now,
                updatedAt = now,
            )
        }
        reminderDao.insertAll(reminders)
    }
}